name: Pull artifacts from another repository

on:
    schedule:
        - cron: '30 6 * * 1' # at 06:30 on monday
    workflow_dispatch:

permissions:
    contents: write
    actions: write

# limit the concurrency of the workflow to one branch
concurrency:
    group: "main"
    cancel-in-progress: false

env:
    GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
    # pull and commit event files
    pull-and-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            # official download-artifact
            # - name: Download the latest event files
            #   uses: actions/download-artifact@v4
            #   with:
            #     # name of the target artifact
            #     name: event_files
            #     # download destination
            #     path: public
            #     github-token: ${{ secrets.GH_PAT }}
            #     repository: songhui-ryu/berlin-event-scraper

            - name: Download the latest event files
              uses: dawidd6/action-download-artifact@v7
              with:
                  github_token: ${{ secrets.GH_PAT }}
                  # path to extract artifact
                  path: public
                  repo: songhui-ryu/berlin-event-scraper
                  branch: main
                  # search the most recent workflow
                  workflow_search: true
                  # name of the target artifact
                  name: events_files

            - name: List files
              run: |
                  ls -al public

            - name: Check for changes
              run: |
                  if git diff --name-only; then
                    echo "Files have been updated"
                  else
                    echo "No changes detected. Exiting..."
                    echo "early_exit=true" >> $GITHUB_ENV
                  fi

            - name: Commit
              if: env.early_exit != 'true'
              run: |
                  git config user.name "github_workflow_bot"
                  git config user.email "bot@users.noreply.github.com"
                  git add public
                  git commit -m "get the latest events from songhui-ryu/berlin-event-scraper"

            - name: Push
              if: env.early_exit != 'true'
              run: git push
